### PR TITLE
automatic data import

### PR DESCRIPTION
**Pull request by stefanocudini**
this PR introduces the functionality of controlling new remote GTFS data and automatic rebuild of the otp graph

some new environment variables are required and described in the README:
**GTFS_URL** gtfs source ftp uri of gtfs .zip file to download
**GTFS_URL_UPDATETIME** gtfs source time interval (default:"daily" possible values: 15min|daily|hourly|monthly|weekly)
**GTFS_URL_UPDATEHOOK** url hook to restart build service

require only a rebuild of **otp** docker container

### CODE REVIEW

**Comment by stefanocudini** [comment]
in subsequent commits I have added:

- updates styles in map
- other fixes by User Interface

**Comment by bertolla** [comment]
@rcavaliere Can you provide this url: GTFS_URL

**Comment by rcavaliere** [comment]
@bertolla ftp://ftp.sta.bz.it/gtfs

**Comment by stefanocudini** [comment]
GTFS_URL it must have url complete with zip file path

@bertolla I'm added this simple fixes in case of GTFS_URL is null, I'm sending you a new PR

https://github.com/openmove/odh-mentor-otp/commit/582a41dfa31fe17b5a9854eed8b48608bb0d86b5

**Pull request merged**
