### PR TITLE
renamed all dot env files

### PR DESCRIPTION
**Pull request by stefanocudini**
@RudiThoeni this fix rebuild of last PR

### CODE REVIEW

**Comment by RudiThoeni** [comment]
Hi @stefanocudini 
it was named .env.example before i saw you renamed this way (_dot.env.example → dotenv.example)
on the prod branch you can see like it was before....

**Comment by stefanocudini** [comment]
Yes exactly

I remember that your environment was having problems with names "_env.xxxxx"

in this way our example files can coexist

**Comment by stefanocudini** [comment]
@RudiThoeni I found the old discussion about it:
https://github.com/noi-techpark/odh-mentor-otp/issues/90#issuecomment-947753738

we have inserted the env example file for human documentation purposes only, we use it as a template file.
As I said in the old discussion it might be useless to make a copy at the time of the build, because the build scripts already insert all the necessary variables.
also very often files may contain unnecessary development informations for prod environment, look here:

https://github.com/noi-techpark/odh-mentor-otp/blob/521ff5a437ffae6d471a462ce129d9d1ba5242ce/infrastructure/Jenkinsfile-Test-Execute.groovy#L71-L126

**Comment by RudiThoeni** [comment]
hi @stefanocudini  ok it is only because it is our standard to have .env.example  ;) but it is no problem,
i merged now and deployed......... seems the application is working.

Before i put to production maybe you can make me a check if everything is working as it should?
Here the startup log of the application 
[startuplogotp.txt](https://github.com/noi-techpark/odh-mentor-otp/files/9268975/startuplogotp.txt)

**Comment by RudiThoeni** [comment]
can i put the two latest PRs to production environment?

**Comment by stefanocudini** [comment]
hi @RudiThoeni I have now finished testing all containers and there are no errors in services

**Pull request merged**
