### PR TITLE
fix journey geocoder

### PR DESCRIPTION
**Pull request by stefanocudini**
small fix that solves a problem in the journey results menu

### CODE REVIEW

**Comment by rcavaliere** [comment]
@stefanocudini thanks! Since you are active on this, can you please provide a feedback on  #75 ?

**Comment by stefanocudini** [comment]
with this PR, i think i solved the problem:
 https://github.com/noi-techpark/odh-mentor-otp/pull/158

the Here API have been changed since we opened this issue many months ago.

our _AppCode_ that we use in the tests of our fork are continuing to work without problems.
But I made this change in the geocoder module to support _AppKey_ because it is useful for the future also for our fork.
Now only appKey is required in the environment variables (_HERE_APIKEY_)

but I would ask you to fix by yourself the part concerning the management of the environment variable in the folder of your infrastructure

**Comment by rcavaliere** [comment]
@stefanocudini perfect! 
@RudiThoeni you can integrate the PR, I will provide the APIKEY in a separate way for your ingestion.

@stefanocudini just another think, am I wrong or in this moment we don't have real-time data? It's a matter of the GTFS-Realtime stream we are using, or it is something related to our implementation?

**Comment by RudiThoeni** [comment]
integrated

**Pull request merged**
