### PR TITLE
new time travel layer

### PR DESCRIPTION
**Pull request by stefanocudini**
- create new service traffic 
- added new interactive layer on journey map (require ne env variable https://github.com/openmove/odh-mentor-otp/blob/development/infrastructure/Jenkinsfile-Test-Execute.groovy#L47)

require a rebuild of journey and run a new container traffic having a subdomain

### CODE REVIEW

**Comment by rcavaliere** [comment]
@RudiThoeni please integrate this PR, but only in the development environment. Thanks @stefanocudini for the update!

**Comment by stefanocudini** [comment]
compared to analytics I tried adding popups with travel times, it could be useful
traffic_traveltime

**Comment by rcavaliere** [comment]
@stefanocudini we also tried this in the past, but from a mobile device this was a mess. Did you try to test this? I am curious to test how you implemented this!

**Comment by stefanocudini** [comment]
hi @rcavaliere I thought of another proposal, see screencast below:
1) only show travel times in case the traffic level is yellow or red on each linkstation
2) no need for popup clicks, but small tooltips are shown instead
3) this continues to give detailed information but without user interaction

if you think it's ok I'll send a PR soon that we can try in development
traffic

**Comment by rcavaliere** [comment]
@stefanocudini that's really cool! yes, let's go in this direction. Is this implemented in this PR or do you still have to implement it? If its already the content of this PR @RudiThoeni let's put this in development and if everything works well let's then go into production

**Comment by stefanocudini** [comment]
just sent a new PR https://github.com/noi-techpark/odh-mentor-otp/pull/137 for this and other little fiexs

**Pull request merged**
