### PR TITLE
Update OTP2 documentation, add elevation data

### PR DESCRIPTION
**Pull request by leonardehrenfried**
This PR updates the documentation about how OTP is built and deployed. I've tried to be careful about not removing useful information and only remove those things that I'm certain are no longer up-to-date.

It also adds elevation data to the OTP graph.

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
cc @dulvui

**Comment by leonardehrenfried** [comment]
As of today, I also added GBFS rental systems.

**Comment by leonardehrenfried** [comment]
@dulvui Is there a deployment of OTP2 somewhere I can take a look?

**Comment by dulvui** [comment]
@leonardehrenfried Great work thank you! Sorry for the late reply.
The test deployment with the custom frontend is running here https://journey.opendatahub.testingmachine.eu
Only the otp service with its standard frontend is running here https://otp.opendatahub.testingmachine.eu

I deployed a first version a few weeks ago, but I will update it now with your latest changes

**Comment by rcavaliere** [comment]
@dulvui @leonardehrenfried I think there is still something to fix, isn't it? If I test the front-end applications, I don't see public transport data retrieved.

**Comment by leonardehrenfried** [comment]
So when I use the OTP debug UI I get results: http://tinyurl.com/27zobf7u

But you're right, in your UI coded against OTP1 I see no results. This is because it is using the deprecated REST API: https://docs.opentripplanner.org/en/dev-2.x/apis/Apis/
 
 I recommend that you don't use this API anymore and migrate to one of the GraphQL APIs. The latest version of digitransit and otp-react-redux use it.

Lastly, I believe you might be able to temporarily make it work by removing the parameter `bannedRoutes` from the URL that the UI sends to OTP. At least this is how I did it: http://tinyurl.com/2co6jr3l

**Pull request merged**
