### PR TITLE
Development

### PR DESCRIPTION
**Pull request by stemove**
@alexlanz @bertolla 

I'm update docs inside README follow the structure of boilerplate

and adding some details( and files like a pregerated osm.url)

### CODE REVIEW

**Comment by alexlanz** [comment]
Thank you @stemove! I was that the folder ` otp-app` is also included in this PR. Do you want to merge it in this PR or was it placed just by mistake?

**Comment by stemove** [comment]
for now we could include it similar to gtfs2bbox directory

The needed config to build it is here:
https://github.com/openmove/odh-mentor-otp/blob/development/docker-compose.yml#L9

**Comment by stemove** [comment]
hi @alexlanz and @bertolla

after this merge as I indicated in the readme
I have simplified the use procedure.
Now every operations is inside docker containers, including:
- generation of the osm.url file with references to osm data relative to the gtfs data
- and the complete download of the data if the DOWNLOAD_DATA variable == True

I recommend for subsequent builds to set DOWNLOAD_DATA = False as this operation I could verify that it takes many minutes

**Comment by bertolla** [comment]
Ok seems to work now and we shipped :rocket: it to our test server.

**Comment by stemove** [comment]
layer
Yes, it works! 
I think that unfortunately the default tile server is down, is more handy to switch to the second layer

**Pull request merged**
