### PR TITLE
Development

### PR DESCRIPTION
**Pull request by stefanocudini**

### CODE REVIEW

**Comment by rcavaliere** [comment]
@stefanocudini thanks for the update, please avoid to use scurrilous words as https://github.com/noi-techpark/odh-mentor-otp/pull/47/commits/00a2ed33deee4a3a3d5b60a88185669cf73ec051 ... :-)

**Comment by stefanocudini** [comment]
> @stefanocudini thanks for the update, please avoid to use scurrilous words as [00a2ed3](https://github.com/noi-techpark/odh-mentor-otp/commit/00a2ed33deee4a3a3d5b60a88185669cf73ec051) ... :-)
@rcavaliere I'm sorry it was a joke thet we forgot to remove :-)
many new commits will come

**Comment by bertolla** [comment]
@stefanocudini 
Before I pull it in, do you want to rename the commit? 
You could still do an interactive rebase und force push it to your fork, if it's not causing to much overhead.

**Comment by stefanocudini** [comment]
just renamed @bertolla many thanks

**Comment by stefanocudini** [comment]
@bertolla about this PR we have introduced a new environment variable that specifies the host name in the new integrated car sharing service:
named: _CARSHARING_HOST_

similar to the other environment variables, docs here:
https://github.com/openmove/odh-mentor-otp/tree/development#docker-environment

**Pull request merged**
