### PR TITLE
first pull

### PR DESCRIPTION
**Pull request by zabuTNT**
docker compose script to build and run an OTP instance

### CODE REVIEW

**Comment by bertolla** [comment]
To also make it clear to Alex, who will setup the test environment, how things should be put in place I wrote a short summary:

We intend to use 2 machines for our environment:
1. Machine number one should expose "opentripplanner" to the enduser which can interact with it and use the routing. For this we thought to use our docker test environment for the development phase.
2. Machine number 2 needs to do heavy calculations to create a Graph for opentripplanner and will therefore only be started when such a calculation is needed. The machine can be started through an API call, does the calculation and shuts down afterwards.

OpenTripPlanner uses the filesystem to store it's data, therefore we will use EFS storage, so that both Machines can access it and performance can be maintained. I already mounted the EFS on the machine number 2 and test-docker-02 on the path /opt/odh-mentor-otp

**Review by bertolla — COMMENTED** [review]
Everything seems fine to me. Alex L. is on vacation this week and will therefore review the documentation and setup the environment next week.
A question which pops in my mind: Is there any kind of testing the code?

**Comment by stemove** [comment]
hi @bertolla  

> Everything seems fine to me. Alex L. is on vacation this week and will therefore review the documentation and setup the environment next week.

I'm adding other details to the documentation about environment vars and more..

> A question which pops in my mind: Is there any kind of testing the code?

not yet, some of the code is not final, I think we can add some unit tests to verify the building of the graph and the download process.
about the building of the graph, the biggest issues that can come out depend a lot on the data broken more than from the code, the amount of code is quite small at the moment to create possibility of bugs.

**Comment by stemove** [comment]
in subsequent commits

I have updated and tried to simplify as much as possible the documentation that explains the steps to follow to instantiate the services

**Comment by alexlanz** [comment]
Hi @stemove! Regarding your question if they have a project that is not java / maven, but instead node. They don't have currently one with node, but they have other projects that have other tools / languages used. Here are some good examples of other projects that also use Docker and can be taken as starting point.

- https://github.com/noi-techpark/authentication-server
- https://github.com/noi-techpark/davinci-innovation-scoreboard-api

Let me know if you need any help or further details.

**Pull request merged**
